require 'json'
require 'faraday'
require 'awesome_print'
require 'colorize'

require_relative './discogs_commander/user_interface'
require_relative './discogs_commander/json_client'
require_relative './discogs_commander/discogs_client'
require_relative './discogs_commander/album_displayer'
require_relative './discogs_commander/artist_displayer'
