require 'bundler/setup'
require 'pry'
require 'json'
require 'faraday'
require 'awesome_print'
require 'colorize'

require_relative './discogs/user_interface'
require_relative './discogs/json_client'
require_relative './discogs/discogs_client'
require_relative './discogs/album_displayer'